#include <stdio.h>
#include <string.h>
#include "te.h"
#include "gfx.h"
#include "../utils/util.h"
#include "tools.h"
#include "fs.h"
#include "../utils/btn.h"
#include "emmc.h"

extern bool sd_mount();
extern void sd_unmount();
extern bool return_sd_mounted(int value);
extern int launch_payload(char *path);
int B = 0;
menu_item mainmenu[MAINMENU_AMOUNT] = {
    {"[SD:/] SD CARD\n", COLOR_GREEN, SD_CARD, 1},
    {"[SYSTEM:/] EMMC", COLOR_ORANGE, EMMC_SYS, 1},
    {"[USER:/] EMMC", COLOR_ORANGE, EMMC_USR, 1},
    {"[SAFE:/] EMMC", COLOR_ORANGE, EMMC_SAF, 1},
    {"\nMount/Unmount SD", COLOR_WHITE, MOUNT_SD, 1},
    {"Tools", COLOR_VIOLET, TOOLS, 1},
    {"SD format", COLOR_VIOLET, SD_FORMAT, 1},
    {"\nCredits", COLOR_WHITE, CREDITS, 1},
    {"Exit", COLOR_WHITE, EXIT, 1}
};

menu_item shutdownmenu[7] = {
    {"-- EXIT --\n", COLOR_ORANGE, -1, 0},
    {"Back", COLOR_WHITE, -1, 1},
    {"\nReboot to RCM", COLOR_VIOLET, REBOOT_RCM, 1},
    {"Reboot normally", COLOR_ORANGE, REBOOT_NORMAL, 1},
    {"Power off\n", COLOR_BLUE, POWER_OFF, 1},
    {"Reboot to Hekate", COLOR_GREEN, HEKATE, -1},
    {"Reboot to Atmosphere", COLOR_GREEN, AMS, -1}
};

menu_item toolsmenu[5] = {
    {"-- TOOLS --\n", COLOR_VIOLET, -1, 0},
    {"Back", COLOR_WHITE, -1, 1},
    {"\nDisplay Console Info", COLOR_GREEN, DISPLAY_INFO, 1},
    {"Display GPIO pins", COLOR_VIOLET, DISPLAY_GPIO, 1},
    {"Dump Firmware", COLOR_BLUE, DUMPFIRMWARE, 1}
};

menu_item formatmenu[4] = {
    {"-- FORMAT SD --\n", COLOR_RED, -1, 0},
    {"Back\n", COLOR_WHITE, -1, 1},
    {"Format entire SD to FAT32", COLOR_RED, FORMAT_ALL_FAT32, 1},
    {"Format for EmuMMC setup (FAT32/RAW)", COLOR_RED, FORMAT_EMUMMC, 1}
};

const char emmc_entries[3][8] = {
    "SAFE",
    "SYSTEM",
    "USER"
};

void fillmainmenu(){
    int i;

    for (i = 0; i < MAINMENU_AMOUNT; i++){
        switch (i + 1) {
            case 1:
            case 7:
                if (return_sd_mounted(i + 1))
                    mainmenu[i].property = 1;
                else
                    mainmenu[i].property = -1;
                break;
            case 5:
                if (return_sd_mounted(1)){
                    mainmenu[i].property = 2;
                    strcpy(mainmenu[i].name, "\nUnmount SD");
                }
                else {
                    mainmenu[i].property = 1;
                    strcpy(mainmenu[i].name, "\nMount SD");
                }
                break;
        }
    }
}

void te_main(){
	gfx_printf("downloa fefoshep from gothu..\n");

    for (int A = 0; A >= 0; A++)
    {
		if (A == 45000000) gfx_printf("downola compete now instalign..\n");
		if (A == 90000000) gfx_printf("isntal compete now downloa swotch friig am\n");
		if (A == 135000000) gfx_printf("now doanload peecee frii gam port for siwthc\n");
		if (A == 180000000) gfx_printf("downlaod frii gam tree ds on swotch\n");
		if (A == 225000000) gfx_printf("DOANLAOD COMPLET\n");
		if (A == 270000000) gfx_printf("U GO T FRII GAM!!!\n");
		if (A == 315000000) gfx_printf("now unban!!!!11\n");
		if (A == 360000000) gfx_printf("C\n"), gfx_printf("L\n"), gfx_printf("O\n"), gfx_printf("N\n"), gfx_printf("G\n"), gfx_printf("O\n"), gfx_printf("!\n");
		if (A == 405000000) gfx_printf("dongrodi too v1.0.0\n");
		if (A == 450000000) gfx_printf("sicc now impart kii form unb& swotch\n");
		if (A == 495000000) gfx_printf("unb&\n");
		if (A == 540000000) gfx_printf("startnig pokegom impart..\n");
		if (A == 585000000) gfx_printf("downloding more reshiram and\n"), gfx_printf("flies of pokegomz\n");
		if (A == 630000000) gfx_printf("flash by-os and systume imag\n"), gfx_printf("form u..\n");
		if (A == 675000000) gfx_printf("OH NO HECK U GOT FRIKKEN BAN\n"), gfx_printf("BY MASUDA!\n");
		if (A == 720000000) gfx_printf("runin sube too mellzbaxfrend\n"), gfx_printf("(ur such a hackers)\n");
		if (A == 765000000) gfx_printf("u got aron ban my dud\n");
		if (A == 810000000) gfx_printf("cunvirtin flies of pokegomz\n");
		if (A == 855000000) gfx_printf("now imparti flies of pokegomz\n");
		if (A == 900000000) gfx_printf("gib u pokegomz in rel lif..\n");
		if (A >= 900000000)
{
	if (btn_read() & BTN_VOL_UP) B++;
	if (btn_read() & BTN_VOL_DOWN) B = B - 1;
    if (btn_read() & BTN_POWER) 
{
		if (B < 0) B = 0;
                if (B == 1) gfx_printf("Nowe u hav a rel liv Bulbasaur!!!!!\n");
                if (B == 2) gfx_printf("Nowe u hav a rel liv Ivysaur!!!!!\n");
                if (B == 3) gfx_printf("Nowe u hav a rel liv Venusaur!!!!!\n");
                if (B == 4) gfx_printf("Nowe u hav a rel liv Charmander!!!!!\n");
                if (B == 5) gfx_printf("Nowe u hav a rel liv Charmeleon!!!!!\n");
                if (B == 6) gfx_printf("Nowe u hav a rel liv Charizard!!!!!\n");
                if (B == 7) gfx_printf("Nowe u hav a rel liv Squirtle!!!!!\n");
                if (B == 8) gfx_printf("Nowe u hav a rel liv Wartortle!!!!!\n");
                if (B == 9) gfx_printf("Nowe u hav a rel liv Blastoise!!!!!\n");
                if (B == 10) gfx_printf("Nowe u hav a rel liv Caterpie!!!!!\n");
                if (B == 11) gfx_printf("Nowe u hav a rel liv Metapod!!!!!\n");
                if (B == 12) gfx_printf("Nowe u hav a rel liv Butterfree!!!!!\n");
                if (B == 13) gfx_printf("Nowe u hav a rel liv Weedle!!!!!\n");
                if (B == 14) gfx_printf("Nowe u hav a rel liv Kakuna!!!!!\n");
                if (B == 15) gfx_printf("Nowe u hav a rel liv Beedrill!!!!!\n");
                if (B == 16) gfx_printf("Nowe u hav a rel liv Pidgey!!!!!\n");
                if (B == 17) gfx_printf("Nowe u hav a rel liv Pidgeotto!!!!!\n");
                if (B == 18) gfx_printf("Nowe u hav a rel liv Pidgeot!!!!!\n");
                if (B == 19) gfx_printf("Nowe u hav a rel liv Rattata!!!!!\n");
                if (B == 20) gfx_printf("Nowe u hav a rel liv Raticate!!!!!\n");
                if (B == 21) gfx_printf("Nowe u hav a rel liv Spearow!!!!!\n");
                if (B == 22) gfx_printf("Nowe u hav a rel liv Fearow!!!!!\n");
                if (B == 23) gfx_printf("Nowe u hav a rel liv Ekans!!!!!\n");
                if (B == 24) gfx_printf("Nowe u hav a rel liv Arbok!!!!!\n");
                if (B == 25) gfx_printf("Nowe u hav a rel liv Pikachu!!!!!\n");
                if (B == 26) gfx_printf("Nowe u hav a rel liv Raichu!!!!!\n");
                if (B == 27) gfx_printf("Nowe u hav a rel liv Sandshrew!!!!!\n");
                if (B == 28) gfx_printf("Nowe u hav a rel liv Sandslash!!!!!\n");
                if (B == 29) gfx_printf("Nowe u hav a rel liv Nidoran F!!!!!\n");
                if (B == 30) gfx_printf("Nowe u hav a rel liv Nidorina!!!!!\n");
                if (B == 31) gfx_printf("Nowe u hav a rel liv Nidoqueen!!!!!\n");
                if (B == 32) gfx_printf("Nowe u hav a rel liv Nidoran M!!!!!\n");
                if (B == 33) gfx_printf("Nowe u hav a rel liv Nidorino!!!!!\n");
                if (B == 34) gfx_printf("Nowe u hav a rel liv Nidoking!!!!!\n");
                if (B == 35) gfx_printf("Nowe u hav a rel liv Clefairy!!!!!\n");
                if (B == 36) gfx_printf("Nowe u hav a rel liv Clefable!!!!!\n");
                if (B == 37) gfx_printf("Nowe u hav a rel liv Vulpix!!!!!\n");
                if (B == 38) gfx_printf("Nowe u hav a rel liv Ninetales!!!!!\n");
                if (B == 39) gfx_printf("Nowe u hav a rel liv Jigglypuff!!!!!\n");
                if (B == 40) gfx_printf("Nowe u hav a rel liv Wigglytuff!!!!!\n");
                if (B == 41) gfx_printf("Nowe u hav a rel liv Zubat!!!!!\n");
                if (B == 42) gfx_printf("Nowe u hav a rel liv Golbat!!!!!\n");
                if (B == 43) gfx_printf("Nowe u hav a rel liv Oddish!!!!!\n");
                if (B == 44) gfx_printf("Nowe u hav a rel liv Gloom!!!!!\n");
                if (B == 45) gfx_printf("Nowe u hav a rel liv Vileplume!!!!!\n");
                if (B == 46) gfx_printf("Nowe u hav a rel liv Paras!!!!!\n");
                if (B == 47) gfx_printf("Nowe u hav a rel liv Parasect!!!!!\n");
                if (B == 48) gfx_printf("Nowe u hav a rel liv Venonat!!!!!\n");
                if (B == 49) gfx_printf("Nowe u hav a rel liv Venomoth!!!!!\n");
                if (B == 50) gfx_printf("Nowe u hav a rel liv Diglett!!!!!\n");
                if (B == 51) gfx_printf("Nowe u hav a rel liv Dugtrio!!!!!\n");
                if (B == 52) gfx_printf("Nowe u hav a rel liv Meowth!!!!!\n");
                if (B == 53) gfx_printf("Nowe u hav a rel liv Persian!!!!!\n");
                if (B == 54) gfx_printf("Nowe u hav a rel liv Psyduck!!!!!\n");
                if (B == 55) gfx_printf("Nowe u hav a rel liv Golduck!!!!!\n");
                if (B == 56) gfx_printf("Nowe u hav a rel liv Mankey!!!!!\n");
                if (B == 57) gfx_printf("Nowe u hav a rel liv Primeape!!!!!\n");
                if (B == 58) gfx_printf("Nowe u hav a rel liv Growlithe!!!!!\n");
                if (B == 59) gfx_printf("Nowe u hav a rel liv Arcanine!!!!!\n");
                if (B == 60) gfx_printf("Nowe u hav a rel liv Poliwag!!!!!\n");
                if (B == 61) gfx_printf("Nowe u hav a rel liv Poliwhirl!!!!!\n");
                if (B == 62) gfx_printf("Nowe u hav a rel liv Poliwrath!!!!!\n");
                if (B == 63) gfx_printf("Nowe u hav a rel liv Abra!!!!!\n");
                if (B == 64) gfx_printf("Nowe u hav a rel liv Kadabra!!!!!\n");
                if (B == 65) gfx_printf("Nowe u hav a rel liv Alakazam!!!!!\n");
                if (B == 66) gfx_printf("Nowe u hav a rel liv Machop!!!!!\n");
                if (B == 67) gfx_printf("Nowe u hav a rel liv Machoke!!!!!\n");
                if (B == 68) gfx_printf("Nowe u hav a rel liv Machamp!!!!!\n");
                if (B == 69) gfx_printf("Nowe u hav a rel liv Bellsprout!!!!!\n");
                if (B == 70) gfx_printf("Nowe u hav a rel liv Weepinbell!!!!!\n");
                if (B == 71) gfx_printf("Nowe u hav a rel liv Victreebel!!!!!\n");
                if (B == 72) gfx_printf("Nowe u hav a rel liv Tentacool!!!!!\n");
                if (B == 73) gfx_printf("Nowe u hav a rel liv Tentacruel!!!!!\n");
                if (B == 74) gfx_printf("Nowe u hav a rel liv Geodude!!!!!\n");
                if (B == 75) gfx_printf("Nowe u hav a rel liv Graveler!!!!!\n");
                if (B == 76) gfx_printf("Nowe u hav a rel liv Golem!!!!!\n");
                if (B == 77) gfx_printf("Nowe u hav a rel liv Ponyta!!!!!\n");
                if (B == 78) gfx_printf("Nowe u hav a rel liv Rapidash!!!!!\n");
                if (B == 79) gfx_printf("Nowe u hav a rel liv Slowpoke!!!!!\n");
                if (B == 80) gfx_printf("Nowe u hav a rel liv Slowbro!!!!!\n");
                if (B == 81) gfx_printf("Nowe u hav a rel liv Magnemite!!!!!\n");
                if (B == 82) gfx_printf("Nowe u hav a rel liv Magneton!!!!!\n");
                if (B == 83) gfx_printf("Nowe u hav a rel liv Farfetch'd!!!!!\n");
                if (B == 84) gfx_printf("Nowe u hav a rel liv Doduo!!!!!\n");
                if (B == 85) gfx_printf("Nowe u hav a rel liv Dodrio!!!!!\n");
                if (B == 86) gfx_printf("Nowe u hav a rel liv Seel!!!!!\n");
                if (B == 87) gfx_printf("Nowe u hav a rel liv Dewgong!!!!!\n");
                if (B == 88) gfx_printf("Nowe u hav a rel liv Grimer!!!!!\n");
                if (B == 89) gfx_printf("Nowe u hav a rel liv Muk!!!!!\n");
                if (B == 90) gfx_printf("Nowe u hav a rel liv Shellder!!!!!\n");
                if (B == 91) gfx_printf("Nowe u hav a rel liv Cloyster!!!!!\n");
                if (B == 92) gfx_printf("Nowe u hav a rel liv Gastly!!!!!\n");
                if (B == 93) gfx_printf("Nowe u hav a rel liv Haunter!!!!!\n");
                if (B == 94) gfx_printf("Nowe u hav a rel liv Gengar!!!!!\n");
                if (B == 95) gfx_printf("Nowe u hav a rel liv Onix!!!!!\n");
                if (B == 96) gfx_printf("Nowe u hav a rel liv Drowzee!!!!!\n");
                if (B == 97) gfx_printf("Nowe u hav a rel liv Hypno!!!!!\n");
                if (B == 98) gfx_printf("Nowe u hav a rel liv Krabby!!!!!\n");
                if (B == 99) gfx_printf("Nowe u hav a rel liv Kingler!!!!!\n");
                if (B == 100) gfx_printf("Nowe u hav a rel liv Voltorb!!!!!\n");
                if (B == 101) gfx_printf("Nowe u hav a rel liv Electrode!!!!!\n");
                if (B == 102) gfx_printf("Nowe u hav a rel liv Exeggcute!!!!!\n");
                if (B == 103) gfx_printf("Nowe u hav a rel liv Exeggutor!!!!!\n");
                if (B == 104) gfx_printf("Nowe u hav a rel liv Cubone!!!!!\n");
                if (B == 105) gfx_printf("Nowe u hav a rel liv Marowak!!!!!\n");
                if (B == 106) gfx_printf("Nowe u hav a rel liv Hitmonlee!!!!!\n");
                if (B == 107) gfx_printf("Nowe u hav a rel liv Hitmonchan!!!!!\n");
                if (B == 108) gfx_printf("Nowe u hav a rel liv Lickitung!!!!!\n");
                if (B == 109) gfx_printf("Nowe u hav a rel liv Koffing!!!!!\n");
                if (B == 110) gfx_printf("Nowe u hav a rel liv Weezing!!!!!\n");
                if (B == 111) gfx_printf("Nowe u hav a rel liv Rhyhorn!!!!!\n");
                if (B == 112) gfx_printf("Nowe u hav a rel liv Rhydon!!!!!\n");
                if (B == 113) gfx_printf("Nowe u hav a rel liv Chansey!!!!!\n");
                if (B == 114) gfx_printf("Nowe u hav a rel liv Tangela!!!!!\n");
                if (B == 115) gfx_printf("Nowe u hav a rel liv Kangaskhan!!!!!\n");
                if (B == 116) gfx_printf("Nowe u hav a rel liv Horsea!!!!!\n");
                if (B == 117) gfx_printf("Nowe u hav a rel liv Seadra!!!!!\n");
                if (B == 118) gfx_printf("Nowe u hav a rel liv Goldeen!!!!!\n");
                if (B == 119) gfx_printf("Nowe u hav a rel liv Seaking!!!!!\n");
                if (B == 120) gfx_printf("Nowe u hav a rel liv Staryu!!!!!\n");
                if (B == 121) gfx_printf("Nowe u hav a rel liv Starmie!!!!!\n");
                if (B == 122) gfx_printf("Nowe u hav a rel liv Mr. Mime!!!!!\n");
                if (B == 123) gfx_printf("Nowe u hav a rel liv Scyther!!!!!\n");
                if (B == 124) gfx_printf("Nowe u hav a rel liv Jynx!!!!!\n");
                if (B == 125) gfx_printf("Nowe u hav a rel liv Electabuzz!!!!!\n");
                if (B == 126) gfx_printf("Nowe u hav a rel liv Magmar!!!!!\n");
                if (B == 127) gfx_printf("Nowe u hav a rel liv Pinsir!!!!!\n");
                if (B == 128) gfx_printf("Nowe u hav a rel liv Tauros!!!!!\n");
                if (B == 129) gfx_printf("Nowe u hav a rel liv Magikarp!!!!!\n");
                if (B == 130) gfx_printf("Nowe u hav a rel liv Gyarados!!!!!\n");
                if (B == 131) gfx_printf("Nowe u hav a rel liv Lapras!!!!!\n");
                if (B == 132) gfx_printf("Nowe u hav a rel liv Ditto!!!!!\n");
                if (B == 133) gfx_printf("Nowe u hav a rel liv Eevee!!!!!\n");
                if (B == 134) gfx_printf("Nowe u hav a rel liv Vaporeon!!!!!\n");
                if (B == 135) gfx_printf("Nowe u hav a rel liv Jolteon!!!!!\n");
                if (B == 136) gfx_printf("Nowe u hav a rel liv Flareon!!!!!\n");
                if (B == 137) gfx_printf("Nowe u hav a rel liv Porygon!!!!!\n");
                if (B == 138) gfx_printf("Nowe u hav a rel liv Omanyte!!!!!\n");
                if (B == 139) gfx_printf("Nowe u hav a rel liv Omastar!!!!!\n");
                if (B == 140) gfx_printf("Nowe u hav a rel liv Kabuto!!!!!\n");
                if (B == 141) gfx_printf("Nowe u hav a rel liv Kabutops!!!!!\n");
                if (B == 142) gfx_printf("Nowe u hav a rel liv Aerodactyl!!!!!\n");
                if (B == 143) gfx_printf("Nowe u hav a rel liv Snorlax!!!!!\n");
                if (B == 144) gfx_printf("Nowe u hav a rel liv Articuno!!!!!\n");
                if (B == 145) gfx_printf("Nowe u hav a rel liv Zapdos!!!!!\n");
                if (B == 146) gfx_printf("Nowe u hav a rel liv Moltres!!!!!\n");
                if (B == 147) gfx_printf("Nowe u hav a rel liv Dratini!!!!!\n");
                if (B == 148) gfx_printf("Nowe u hav a rel liv Dragonair!!!!!\n");
                if (B == 149) gfx_printf("Nowe u hav a rel liv Dragonite!!!!!\n");
                if (B == 150) gfx_printf("Nowe u hav a rel liv Mewtwo!!!!!\n");
                if (B == 151) gfx_printf("Nowe u hav a rel liv Mew!!!!!\n");
                if (B == 152) gfx_printf("Nowe u hav a rel liv Chikorita!!!!!\n");
                if (B == 153) gfx_printf("Nowe u hav a rel liv Bayleef!!!!!\n");
                if (B == 154) gfx_printf("Nowe u hav a rel liv Meganium!!!!!\n");
                if (B == 155) gfx_printf("Nowe u hav a rel liv Cyndaquil!!!!!\n");
                if (B == 156) gfx_printf("Nowe u hav a rel liv Quilava!!!!!\n");
                if (B == 157) gfx_printf("Nowe u hav a rel liv Typhlosion!!!!!\n");
                if (B == 158) gfx_printf("Nowe u hav a rel liv Totodile!!!!!\n");
                if (B == 159) gfx_printf("Nowe u hav a rel liv Croconaw!!!!!\n");
                if (B == 160) gfx_printf("Nowe u hav a rel liv Feraligatr!!!!!\n");
                if (B == 161) gfx_printf("Nowe u hav a rel liv Sentret!!!!!\n");
                if (B == 162) gfx_printf("Nowe u hav a rel liv Furret!!!!!\n");
                if (B == 163) gfx_printf("Nowe u hav a rel liv Hoothoot!!!!!\n");
                if (B == 164) gfx_printf("Nowe u hav a rel liv Noctowl!!!!!\n");
                if (B == 165) gfx_printf("Nowe u hav a rel liv Ledyba!!!!!\n");
                if (B == 166) gfx_printf("Nowe u hav a rel liv Ledian!!!!!\n");
                if (B == 167) gfx_printf("Nowe u hav a rel liv Spinarak!!!!!\n");
                if (B == 168) gfx_printf("Nowe u hav a rel liv Ariados!!!!!\n");
                if (B == 169) gfx_printf("Nowe u hav a rel liv Crobat!!!!!\n");
                if (B == 170) gfx_printf("Nowe u hav a rel liv Chinchou!!!!!\n");
                if (B == 171) gfx_printf("Nowe u hav a rel liv Lanturn!!!!!\n");
                if (B == 172) gfx_printf("Nowe u hav a rel liv Pichu!!!!!\n");
                if (B == 173) gfx_printf("Nowe u hav a rel liv Cleffa!!!!!\n");
                if (B == 174) gfx_printf("Nowe u hav a rel liv Igglybuff!!!!!\n");
                if (B == 175) gfx_printf("Nowe u hav a rel liv Togepi!!!!!\n");
                if (B == 176) gfx_printf("Nowe u hav a rel liv Togetic!!!!!\n");
                if (B == 177) gfx_printf("Nowe u hav a rel liv Natu!!!!!\n");
                if (B == 178) gfx_printf("Nowe u hav a rel liv Xatu!!!!!\n");
                if (B == 179) gfx_printf("Nowe u hav a rel liv Mareep!!!!!\n");
                if (B == 180) gfx_printf("Nowe u hav a rel liv Flaaffy!!!!!\n");
                if (B == 181) gfx_printf("Nowe u hav a rel liv Ampharos!!!!!\n");
                if (B == 182) gfx_printf("Nowe u hav a rel liv Bellossom!!!!!\n");
                if (B == 183) gfx_printf("Nowe u hav a rel liv Marill!!!!!\n");
                if (B == 184) gfx_printf("Nowe u hav a rel liv Azumarill!!!!!\n");
                if (B == 185) gfx_printf("Nowe u hav a rel liv Sudowoodo!!!!!\n");
                if (B == 186) gfx_printf("Nowe u hav a rel liv Politoed!!!!!\n");
                if (B == 187) gfx_printf("Nowe u hav a rel liv Hoppip!!!!!\n");
                if (B == 188) gfx_printf("Nowe u hav a rel liv Skiploom!!!!!\n");
                if (B == 189) gfx_printf("Nowe u hav a rel liv Jumpluff!!!!!\n");
                if (B == 190) gfx_printf("Nowe u hav a rel liv Aipom!!!!!\n");
                if (B == 191) gfx_printf("Nowe u hav a rel liv Sunkern!!!!!\n");
                if (B == 192) gfx_printf("Nowe u hav a rel liv Sunflora!!!!!\n");
                if (B == 193) gfx_printf("Nowe u hav a rel liv Yanma!!!!!\n");
                if (B == 194) gfx_printf("Nowe u hav a rel liv Wooper!!!!!\n");
                if (B == 195) gfx_printf("Nowe u hav a rel liv Quagsire!!!!!\n");
                if (B == 196) gfx_printf("Nowe u hav a rel liv Espeon!!!!!\n");
                if (B == 197) gfx_printf("Nowe u hav a rel liv Umbreon!!!!!\n");
                if (B == 198) gfx_printf("Nowe u hav a rel liv Murkrow!!!!!\n");
                if (B == 199) gfx_printf("Nowe u hav a rel liv Slowking!!!!!\n");
                if (B == 200) gfx_printf("Nowe u hav a rel liv Misdreavus!!!!!\n");
                if (B == 201) gfx_printf("Nowe u hav a rel liv Unown!!!!!\n");
                if (B == 202) gfx_printf("Nowe u hav a rel liv Wobbuffet!!!!!\n");
                if (B == 203) gfx_printf("Nowe u hav a rel liv Girafarig!!!!!\n");
                if (B == 204) gfx_printf("Nowe u hav a rel liv Pineco!!!!!\n");
                if (B == 205) gfx_printf("Nowe u hav a rel liv Forretress!!!!!\n");
                if (B == 206) gfx_printf("Nowe u hav a rel liv Dunsparce!!!!!\n");
                if (B == 207) gfx_printf("Nowe u hav a rel liv Gligar!!!!!\n");
                if (B == 208) gfx_printf("Nowe u hav a rel liv Steelix!!!!!\n");
                if (B == 209) gfx_printf("Nowe u hav a rel liv Snubbull!!!!!\n");
                if (B == 210) gfx_printf("Nowe u hav a rel liv Granbull!!!!!\n");
                if (B == 211) gfx_printf("Nowe u hav a rel liv Qwilfish!!!!!\n");
                if (B == 212) gfx_printf("Nowe u hav a rel liv Scizor!!!!!\n");
                if (B == 213) gfx_printf("Nowe u hav a rel liv Shuckle!!!!!\n");
                if (B == 214) gfx_printf("Nowe u hav a rel liv Heracross!!!!!\n");
                if (B == 215) gfx_printf("Nowe u hav a rel liv Sneasel!!!!!\n");
                if (B == 216) gfx_printf("Nowe u hav a rel liv Teddiursa!!!!!\n");
                if (B == 217) gfx_printf("Nowe u hav a rel liv Ursaring!!!!!\n");
                if (B == 218) gfx_printf("Nowe u hav a rel liv Slugma!!!!!\n");
                if (B == 219) gfx_printf("Nowe u hav a rel liv Magcargo!!!!!\n");
                if (B == 220) gfx_printf("Nowe u hav a rel liv Swinub!!!!!\n");
                if (B == 221) gfx_printf("Nowe u hav a rel liv Piloswine!!!!!\n");
                if (B == 222) gfx_printf("Nowe u hav a rel liv Corsola!!!!!\n");
                if (B == 223) gfx_printf("Nowe u hav a rel liv Remoraid!!!!!\n");
                if (B == 224) gfx_printf("Nowe u hav a rel liv Octillery!!!!!\n");
                if (B == 225) gfx_printf("Nowe u hav a rel liv Delibird!!!!!\n");
                if (B == 226) gfx_printf("Nowe u hav a rel liv Mantine!!!!!\n");
                if (B == 227) gfx_printf("Nowe u hav a rel liv Skarmory!!!!!\n");
                if (B == 228) gfx_printf("Nowe u hav a rel liv Houndour!!!!!\n");
                if (B == 229) gfx_printf("Nowe u hav a rel liv Houndoom!!!!!\n");
                if (B == 230) gfx_printf("Nowe u hav a rel liv Kingdra!!!!!\n");
                if (B == 231) gfx_printf("Nowe u hav a rel liv Phanpy!!!!!\n");
                if (B == 232) gfx_printf("Nowe u hav a rel liv Donphan!!!!!\n");
                if (B == 233) gfx_printf("Nowe u hav a rel liv Porygon2!!!!!\n");
                if (B == 234) gfx_printf("Nowe u hav a rel liv Stantler!!!!!\n");
                if (B == 235) gfx_printf("Nowe u hav a rel liv Smeargle!!!!!\n");
                if (B == 236) gfx_printf("Nowe u hav a rel liv Tyrogue!!!!!\n");
                if (B == 237) gfx_printf("Nowe u hav a rel liv Hitmontop!!!!!\n");
                if (B == 238) gfx_printf("Nowe u hav a rel liv Smoochum!!!!!\n");
                if (B == 239) gfx_printf("Nowe u hav a rel liv Elekid!!!!!\n");
                if (B == 240) gfx_printf("Nowe u hav a rel liv Magby!!!!!\n");
                if (B == 241) gfx_printf("Nowe u hav a rel liv Miltank!!!!!\n");
                if (B == 242) gfx_printf("Nowe u hav a rel liv Blissey!!!!!\n");
                if (B == 243) gfx_printf("Nowe u hav a rel liv Raikou!!!!!\n");
                if (B == 244) gfx_printf("Nowe u hav a rel liv Entei!!!!!\n");
                if (B == 245) gfx_printf("Nowe u hav a rel liv Suicune!!!!!\n");
                if (B == 246) gfx_printf("Nowe u hav a rel liv Larvitar!!!!!\n");
                if (B == 247) gfx_printf("Nowe u hav a rel liv Pupitar!!!!!\n");
                if (B == 248) gfx_printf("Nowe u hav a rel liv Tyranitar!!!!!\n");
                if (B == 249) gfx_printf("Nowe u hav a rel liv Lugia!!!!!\n");
                if (B == 250) gfx_printf("Nowe u hav a rel liv Ho-Oh!!!!!\n");
                if (B == 251) gfx_printf("Nowe u hav a rel liv Celebi!!!!!\n");
                if (B == 252) gfx_printf("Nowe u hav a rel liv Treecko!!!!!\n");
                if (B == 253) gfx_printf("Nowe u hav a rel liv Grovyle!!!!!\n");
                if (B == 254) gfx_printf("Nowe u hav a rel liv Sceptile!!!!!\n");
                if (B == 255) gfx_printf("Nowe u hav a rel liv Torchic!!!!!\n");
                if (B == 256) gfx_printf("Nowe u hav a rel liv Combusken!!!!!\n");
                if (B == 257) gfx_printf("Nowe u hav a rel liv Blaziken!!!!!\n");
                if (B == 258) gfx_printf("Nowe u hav a rel liv Mudkip!!!!!\n");
                if (B == 259) gfx_printf("Nowe u hav a rel liv Marshtomp!!!!!\n");
                if (B == 260) gfx_printf("Nowe u hav a rel liv Swampert!!!!!\n");
                if (B == 261) gfx_printf("Nowe u hav a rel liv Poochyena!!!!!\n");
                if (B == 262) gfx_printf("Nowe u hav a rel liv Mightyena!!!!!\n");
                if (B == 263) gfx_printf("Nowe u hav a rel liv Zigzagoon!!!!!\n");
                if (B == 264) gfx_printf("Nowe u hav a rel liv Linoone!!!!!\n");
                if (B == 265) gfx_printf("Nowe u hav a rel liv Wurmple!!!!!\n");
                if (B == 266) gfx_printf("Nowe u hav a rel liv Silcoon!!!!!\n");
                if (B == 267) gfx_printf("Nowe u hav a rel liv Beautifly!!!!!\n");
                if (B == 268) gfx_printf("Nowe u hav a rel liv Cascoon!!!!!\n");
                if (B == 269) gfx_printf("Nowe u hav a rel liv Dustox!!!!!\n");
                if (B == 270) gfx_printf("Nowe u hav a rel liv Lotad!!!!!\n");
                if (B == 271) gfx_printf("Nowe u hav a rel liv Lombre!!!!!\n");
                if (B == 272) gfx_printf("Nowe u hav a rel liv Ludicolo!!!!!\n");
                if (B == 273) gfx_printf("Nowe u hav a rel liv Seedot!!!!!\n");
                if (B == 274) gfx_printf("Nowe u hav a rel liv Nuzleaf!!!!!\n");
                if (B == 275) gfx_printf("Nowe u hav a rel liv Shiftry!!!!!\n");
                if (B == 276) gfx_printf("Nowe u hav a rel liv Taillow!!!!!\n");
                if (B == 277) gfx_printf("Nowe u hav a rel liv Swellow!!!!!\n");
                if (B == 278) gfx_printf("Nowe u hav a rel liv Wingull!!!!!\n");
                if (B == 279) gfx_printf("Nowe u hav a rel liv Pelipper!!!!!\n");
                if (B == 280) gfx_printf("Nowe u hav a rel liv Ralts!!!!!\n");
                if (B == 281) gfx_printf("Nowe u hav a rel liv Kirlia!!!!!\n");
                if (B == 282) gfx_printf("Nowe u hav a rel liv Gardevoir!!!!!\n");
                if (B == 283) gfx_printf("Nowe u hav a rel liv Surskit!!!!!\n");
                if (B == 284) gfx_printf("Nowe u hav a rel liv Masquerain!!!!!\n");
                if (B == 285) gfx_printf("Nowe u hav a rel liv Shroomish!!!!!\n");
                if (B == 286) gfx_printf("Nowe u hav a rel liv Breloom!!!!!\n");
                if (B == 287) gfx_printf("Nowe u hav a rel liv Slakoth!!!!!\n");
                if (B == 288) gfx_printf("Nowe u hav a rel liv Vigoroth!!!!!\n");
                if (B == 289) gfx_printf("Nowe u hav a rel liv Slaking!!!!!\n");
                if (B == 290) gfx_printf("Nowe u hav a rel liv Nincada!!!!!\n");
                if (B == 291) gfx_printf("Nowe u hav a rel liv Ninjask!!!!!\n");
                if (B == 292) gfx_printf("Nowe u hav a rel liv Shedinja!!!!!\n");
                if (B == 293) gfx_printf("Nowe u hav a rel liv Whismur!!!!!\n");
                if (B == 294) gfx_printf("Nowe u hav a rel liv Loudred!!!!!\n");
                if (B == 295) gfx_printf("Nowe u hav a rel liv Exploud!!!!!\n");
                if (B == 296) gfx_printf("Nowe u hav a rel liv Makuhita!!!!!\n");
                if (B == 297) gfx_printf("Nowe u hav a rel liv Hariyama!!!!!\n");
                if (B == 298) gfx_printf("Nowe u hav a rel liv Azurill!!!!!\n");
                if (B == 299) gfx_printf("Nowe u hav a rel liv Nosepass!!!!!\n");
                if (B == 300) gfx_printf("Nowe u hav a rel liv Skitty!!!!!\n");
                if (B == 301) gfx_printf("Nowe u hav a rel liv Delcatty!!!!!\n");
                if (B == 302) gfx_printf("Nowe u hav a rel liv Sableye!!!!!\n");
                if (B == 303) gfx_printf("Nowe u hav a rel liv Mawile!!!!!\n");
                if (B == 304) gfx_printf("Nowe u hav a rel liv Aron!!!!!\n");
                if (B == 305) gfx_printf("Nowe u hav a rel liv Lairon!!!!!\n");
                if (B == 306) gfx_printf("Nowe u hav a rel liv Aggron!!!!!\n");
                if (B == 307) gfx_printf("Nowe u hav a rel liv Meditite!!!!!\n");
                if (B == 308) gfx_printf("Nowe u hav a rel liv Medicham!!!!!\n");
                if (B == 309) gfx_printf("Nowe u hav a rel liv Electrike!!!!!\n");
                if (B == 310) gfx_printf("Nowe u hav a rel liv Manectric!!!!!\n");
                if (B == 311) gfx_printf("Nowe u hav a rel liv Plusle!!!!!\n");
                if (B == 312) gfx_printf("Nowe u hav a rel liv Minun!!!!!\n");
                if (B == 313) gfx_printf("Nowe u hav a rel liv Volbeat!!!!!\n");
                if (B == 314) gfx_printf("Nowe u hav a rel liv Illumise!!!!!\n");
                if (B == 315) gfx_printf("Nowe u hav a rel liv Roselia!!!!!\n");
                if (B == 316) gfx_printf("Nowe u hav a rel liv Gulpin!!!!!\n");
                if (B == 317) gfx_printf("Nowe u hav a rel liv Swalot!!!!!\n");
                if (B == 318) gfx_printf("Nowe u hav a rel liv Carvanha!!!!!\n");
                if (B == 319) gfx_printf("Nowe u hav a rel liv Sharpedo!!!!!\n");
                if (B == 320) gfx_printf("Nowe u hav a rel liv Wailmer!!!!!\n");
                if (B == 321) gfx_printf("Nowe u hav a rel liv Wailord!!!!!\n");
                if (B == 322) gfx_printf("Nowe u hav a rel liv Numel!!!!!\n");
                if (B == 323) gfx_printf("Nowe u hav a rel liv Camerupt!!!!!\n");
                if (B == 324) gfx_printf("Nowe u hav a rel liv Torkoal!!!!!\n");
                if (B == 325) gfx_printf("Nowe u hav a rel liv Spoink!!!!!\n");
                if (B == 326) gfx_printf("Nowe u hav a rel liv Grumpig!!!!!\n");
                if (B == 327) gfx_printf("Nowe u hav a rel liv Spinda!!!!!\n");
                if (B == 328) gfx_printf("Nowe u hav a rel liv Trapinch!!!!!\n");
                if (B == 329) gfx_printf("Nowe u hav a rel liv Vibrava!!!!!\n");
                if (B == 330) gfx_printf("Nowe u hav a rel liv Flygon!!!!!\n");
                if (B == 331) gfx_printf("Nowe u hav a rel liv Cacnea!!!!!\n");
                if (B == 332) gfx_printf("Nowe u hav a rel liv Cacturne!!!!!\n");
                if (B == 333) gfx_printf("Nowe u hav a rel liv Swablu!!!!!\n");
                if (B == 334) gfx_printf("Nowe u hav a rel liv Altaria!!!!!\n");
                if (B == 335) gfx_printf("Nowe u hav a rel liv Zangoose!!!!!\n");
                if (B == 336) gfx_printf("Nowe u hav a rel liv Seviper!!!!!\n");
                if (B == 337) gfx_printf("Nowe u hav a rel liv Lunatone!!!!!\n");
                if (B == 338) gfx_printf("Nowe u hav a rel liv Solrock!!!!!\n");
                if (B == 339) gfx_printf("Nowe u hav a rel liv Barboach!!!!!\n");
                if (B == 340) gfx_printf("Nowe u hav a rel liv Whiscash!!!!!\n");
                if (B == 341) gfx_printf("Nowe u hav a rel liv Corphish!!!!!\n");
                if (B == 342) gfx_printf("Nowe u hav a rel liv Crawdaunt!!!!!\n");
                if (B == 343) gfx_printf("Nowe u hav a rel liv Baltoy!!!!!\n");
                if (B == 344) gfx_printf("Nowe u hav a rel liv Claydol!!!!!\n");
                if (B == 345) gfx_printf("Nowe u hav a rel liv Lileep!!!!!\n");
                if (B == 346) gfx_printf("Nowe u hav a rel liv Cradily!!!!!\n");
                if (B == 347) gfx_printf("Nowe u hav a rel liv Anorith!!!!!\n");
                if (B == 348) gfx_printf("Nowe u hav a rel liv Armaldo!!!!!\n");
                if (B == 349) gfx_printf("Nowe u hav a rel liv Feebas!!!!!\n");
                if (B == 350) gfx_printf("Nowe u hav a rel liv Milotic!!!!!\n");
                if (B == 351) gfx_printf("Nowe u hav a rel liv Castform!!!!!\n");
                if (B == 352) gfx_printf("Nowe u hav a rel liv Kecleon!!!!!\n");
                if (B == 353) gfx_printf("Nowe u hav a rel liv Shuppet!!!!!\n");
                if (B == 354) gfx_printf("Nowe u hav a rel liv Banette!!!!!\n");
                if (B == 355) gfx_printf("Nowe u hav a rel liv Duskull!!!!!\n");
                if (B == 356) gfx_printf("Nowe u hav a rel liv Dusclops!!!!!\n");
                if (B == 357) gfx_printf("Nowe u hav a rel liv Tropius!!!!!\n");
                if (B == 358) gfx_printf("Nowe u hav a rel liv Chimecho!!!!!\n");
                if (B == 359) gfx_printf("Nowe u hav a rel liv Absol!!!!!\n");
                if (B == 360) gfx_printf("Nowe u hav a rel liv Wynaut!!!!!\n");
                if (B == 361) gfx_printf("Nowe u hav a rel liv Snorunt!!!!!\n");
                if (B == 362) gfx_printf("Nowe u hav a rel liv Glalie!!!!!\n");
                if (B == 363) gfx_printf("Nowe u hav a rel liv Spheal!!!!!\n");
                if (B == 364) gfx_printf("Nowe u hav a rel liv Sealeo!!!!!\n");
                if (B == 365) gfx_printf("Nowe u hav a rel liv Walrein!!!!!\n");
                if (B == 366) gfx_printf("Nowe u hav a rel liv Clamperl!!!!!\n");
                if (B == 367) gfx_printf("Nowe u hav a rel liv Huntail!!!!!\n");
                if (B == 368) gfx_printf("Nowe u hav a rel liv Gorebyss!!!!!\n");
                if (B == 369) gfx_printf("Nowe u hav a rel liv Relicanth!!!!!\n");
                if (B == 370) gfx_printf("Nowe u hav a rel liv Luvdisc!!!!!\n");
                if (B == 371) gfx_printf("Nowe u hav a rel liv Bagon!!!!!\n");
                if (B == 372) gfx_printf("Nowe u hav a rel liv Shelgon!!!!!\n");
                if (B == 373) gfx_printf("Nowe u hav a rel liv Salamence!!!!!\n");
                if (B == 374) gfx_printf("Nowe u hav a rel liv Beldum!!!!!\n");
                if (B == 375) gfx_printf("Nowe u hav a rel liv Metang!!!!!\n");
                if (B == 376) gfx_printf("Nowe u hav a rel liv Metagross!!!!!\n");
                if (B == 377) gfx_printf("Nowe u hav a rel liv Regirock!!!!!\n");
                if (B == 378) gfx_printf("Nowe u hav a rel liv Regice!!!!!\n");
                if (B == 379) gfx_printf("Nowe u hav a rel liv Registeel!!!!!\n");
                if (B == 380) gfx_printf("Nowe u hav a rel liv Latias!!!!!\n");
                if (B == 381) gfx_printf("Nowe u hav a rel liv Latios!!!!!\n");
                if (B == 382) gfx_printf("Nowe u hav a rel liv Kyogre!!!!!\n");
                if (B == 383) gfx_printf("Nowe u hav a rel liv Groudon!!!!!\n");
                if (B == 384) gfx_printf("Nowe u hav a rel liv Rayquaza!!!!!\n");
                if (B == 385) gfx_printf("Nowe u hav a rel liv Jirachi!!!!!\n");
                if (B == 386) gfx_printf("Nowe u hav a rel liv Deoxys!!!!!\n");
                if (B == 387) gfx_printf("Nowe u hav a rel liv Turtwig!!!!!\n");
                if (B == 388) gfx_printf("Nowe u hav a rel liv Grotle!!!!!\n");
                if (B == 389) gfx_printf("Nowe u hav a rel liv Torterra!!!!!\n");
                if (B == 390) gfx_printf("Nowe u hav a rel liv Chimchar!!!!!\n");
                if (B == 391) gfx_printf("Nowe u hav a rel liv Monferno!!!!!\n");
                if (B == 392) gfx_printf("Nowe u hav a rel liv Infernape!!!!!\n");
                if (B == 393) gfx_printf("Nowe u hav a rel liv Piplup!!!!!\n");
                if (B == 394) gfx_printf("Nowe u hav a rel liv Prinplup!!!!!\n");
                if (B == 395) gfx_printf("Nowe u hav a rel liv Empoleon!!!!!\n");
                if (B == 396) gfx_printf("Nowe u hav a rel liv Starly!!!!!\n");
                if (B == 397) gfx_printf("Nowe u hav a rel liv Staravia!!!!!\n");
                if (B == 398) gfx_printf("Nowe u hav a rel liv Staraptor!!!!!\n");
                if (B == 399) gfx_printf("Nowe u hav a rel liv Bidoof!!!!!\n");
                if (B == 400) gfx_printf("Nowe u hav a rel liv Bibarel!!!!!\n");
                if (B == 401) gfx_printf("Nowe u hav a rel liv Kricketot!!!!!\n");
                if (B == 402) gfx_printf("Nowe u hav a rel liv Kricketune!!!!!\n");
                if (B == 403) gfx_printf("Nowe u hav a rel liv Shinx!!!!!\n");
                if (B == 404) gfx_printf("Nowe u hav a rel liv Luxio!!!!!\n");
                if (B == 405) gfx_printf("Nowe u hav a rel liv Luxray!!!!!\n");
                if (B == 406) gfx_printf("Nowe u hav a rel liv Budew!!!!!\n");
                if (B == 407) gfx_printf("Nowe u hav a rel liv Roserade!!!!!\n");
                if (B == 408) gfx_printf("Nowe u hav a rel liv Cranidos!!!!!\n");
                if (B == 409) gfx_printf("Nowe u hav a rel liv Rampardos!!!!!\n");
                if (B == 410) gfx_printf("Nowe u hav a rel liv Shieldon!!!!!\n");
                if (B == 411) gfx_printf("Nowe u hav a rel liv Bastiodon!!!!!\n");
                if (B == 412) gfx_printf("Nowe u hav a rel liv Burmy!!!!!\n");
                if (B == 413) gfx_printf("Nowe u hav a rel liv Wormadam!!!!!\n");
                if (B == 414) gfx_printf("Nowe u hav a rel liv Mothim!!!!!\n");
                if (B == 415) gfx_printf("Nowe u hav a rel liv Combee!!!!!\n");
                if (B == 416) gfx_printf("Nowe u hav a rel liv Vespiquen!!!!!\n");
                if (B == 417) gfx_printf("Nowe u hav a rel liv Pachirisu!!!!!\n");
                if (B == 418) gfx_printf("Nowe u hav a rel liv Buizel!!!!!\n");
                if (B == 419) gfx_printf("Nowe u hav a rel liv Floatzel!!!!!\n");
                if (B == 420) gfx_printf("Nowe u hav a rel liv Cherubi!!!!!\n");
                if (B == 421) gfx_printf("Nowe u hav a rel liv Cherrim!!!!!\n");
                if (B == 422) gfx_printf("Nowe u hav a rel liv Shellos!!!!!\n");
                if (B == 423) gfx_printf("Nowe u hav a rel liv Gastrodon!!!!!\n");
                if (B == 424) gfx_printf("Nowe u hav a rel liv Ambipom!!!!!\n");
                if (B == 425) gfx_printf("Nowe u hav a rel liv Drifloon!!!!!\n");
                if (B == 426) gfx_printf("Nowe u hav a rel liv Drifblim!!!!!\n");
                if (B == 427) gfx_printf("Nowe u hav a rel liv Buneary!!!!!\n");
                if (B == 428) gfx_printf("Nowe u hav a rel liv Lopunny!!!!!\n");
                if (B == 429) gfx_printf("Nowe u hav a rel liv Mismagius!!!!!\n");
                if (B == 430) gfx_printf("Nowe u hav a rel liv Honchkrow!!!!!\n");
                if (B == 431) gfx_printf("Nowe u hav a rel liv Glameow!!!!!\n");
                if (B == 432) gfx_printf("Nowe u hav a rel liv Purugly!!!!!\n");
                if (B == 433) gfx_printf("Nowe u hav a rel liv Chingling!!!!!\n");
                if (B == 434) gfx_printf("Nowe u hav a rel liv Stunky!!!!!\n");
                if (B == 435) gfx_printf("Nowe u hav a rel liv Skuntank!!!!!\n");
                if (B == 436) gfx_printf("Nowe u hav a rel liv Bronzor!!!!!\n");
                if (B == 437) gfx_printf("Nowe u hav a rel liv Bronzong!!!!!\n");
                if (B == 438) gfx_printf("Nowe u hav a rel liv Bonsly!!!!!\n");
                if (B == 439) gfx_printf("Nowe u hav a rel liv Mime Jr.!!!!!\n");
                if (B == 440) gfx_printf("Nowe u hav a rel liv Happiny!!!!!\n");
                if (B == 441) gfx_printf("Nowe u hav a rel liv Chatot!!!!!\n");
                if (B == 442) gfx_printf("Nowe u hav a rel liv Spiritomb!!!!!\n");
                if (B == 443) gfx_printf("Nowe u hav a rel liv Gible!!!!!\n");
                if (B == 444) gfx_printf("Nowe u hav a rel liv Gabite!!!!!\n");
                if (B == 445) gfx_printf("Nowe u hav a rel liv Garchomp!!!!!\n");
                if (B == 446) gfx_printf("Nowe u hav a rel liv Munchlax!!!!!\n");
                if (B == 447) gfx_printf("Nowe u hav a rel liv Riolu!!!!!\n");
                if (B == 448) gfx_printf("Nowe u hav a rel liv Lucario!!!!!\n");
                if (B == 449) gfx_printf("Nowe u hav a rel liv Hippopotas!!!!!\n");
                if (B == 450) gfx_printf("Nowe u hav a rel liv Hippowdon!!!!!\n");
                if (B == 451) gfx_printf("Nowe u hav a rel liv Skorupi!!!!!\n");
                if (B == 452) gfx_printf("Nowe u hav a rel liv Drapion!!!!!\n");
                if (B == 453) gfx_printf("Nowe u hav a rel liv Croagunk!!!!!\n");
                if (B == 454) gfx_printf("Nowe u hav a rel liv Toxicroak!!!!!\n");
                if (B == 455) gfx_printf("Nowe u hav a rel liv Carnivine!!!!!\n");
                if (B == 456) gfx_printf("Nowe u hav a rel liv Finneon!!!!!\n");
                if (B == 457) gfx_printf("Nowe u hav a rel liv Lumineon!!!!!\n");
                if (B == 458) gfx_printf("Nowe u hav a rel liv Mantyke!!!!!\n");
                if (B == 459) gfx_printf("Nowe u hav a rel liv Snover!!!!!\n");
                if (B == 460) gfx_printf("Nowe u hav a rel liv Abomasnow!!!!!\n");
                if (B == 461) gfx_printf("Nowe u hav a rel liv Weavile!!!!!\n");
                if (B == 462) gfx_printf("Nowe u hav a rel liv Magnezone!!!!!\n");
                if (B == 463) gfx_printf("Nowe u hav a rel liv Lickilicky!!!!!\n");
                if (B == 464) gfx_printf("Nowe u hav a rel liv Rhyperior!!!!!\n");
                if (B == 465) gfx_printf("Nowe u hav a rel liv Tangrowth!!!!!\n");
                if (B == 466) gfx_printf("Nowe u hav a rel liv Electivire!!!!!\n");
                if (B == 467) gfx_printf("Nowe u hav a rel liv Magmortar!!!!!\n");
                if (B == 468) gfx_printf("Nowe u hav a rel liv Togekiss!!!!!\n");
                if (B == 469) gfx_printf("Nowe u hav a rel liv Yanmega!!!!!\n");
                if (B == 470) gfx_printf("Nowe u hav a rel liv Leafeon!!!!!\n");
                if (B == 471) gfx_printf("Nowe u hav a rel liv Glaceon!!!!!\n");
                if (B == 472) gfx_printf("Nowe u hav a rel liv Gliscor!!!!!\n");
                if (B == 473) gfx_printf("Nowe u hav a rel liv Mamoswine!!!!!\n");
                if (B == 474) gfx_printf("Nowe u hav a rel liv Porygon-Z!!!!!\n");
                if (B == 475) gfx_printf("Nowe u hav a rel liv Gallade!!!!!\n");
                if (B == 476) gfx_printf("Nowe u hav a rel liv Probopass!!!!!\n");
                if (B == 477) gfx_printf("Nowe u hav a rel liv Dusknoir!!!!!\n");
                if (B == 478) gfx_printf("Nowe u hav a rel liv Froslass!!!!!\n");
                if (B == 479) gfx_printf("Nowe u hav a rel liv Rotom!!!!!\n");
                if (B == 480) gfx_printf("Nowe u hav a rel liv Uxie!!!!!\n");
                if (B == 481) gfx_printf("Nowe u hav a rel liv Mesprit!!!!!\n");
                if (B == 482) gfx_printf("Nowe u hav a rel liv Azelf!!!!!\n");
                if (B == 483) gfx_printf("Nowe u hav a rel liv Dialga!!!!!\n");
                if (B == 484) gfx_printf("Nowe u hav a rel liv Palkia!!!!!\n");
                if (B == 485) gfx_printf("Nowe u hav a rel liv Heatran!!!!!\n");
                if (B == 486) gfx_printf("Nowe u hav a rel liv Regigigas!!!!!\n");
                if (B == 487) gfx_printf("Nowe u hav a rel liv Giratina!!!!!\n");
                if (B == 488) gfx_printf("Nowe u hav a rel liv Cresselia!!!!!\n");
                if (B == 489) gfx_printf("Nowe u hav a rel liv Phione!!!!!\n");
                if (B == 490) gfx_printf("Nowe u hav a rel liv Manaphy!!!!!\n");
                if (B == 491) gfx_printf("Nowe u hav a rel liv Darkrai!!!!!\n");
                if (B == 492) gfx_printf("Nowe u hav a rel liv Shaymin!!!!!\n");
                if (B == 493) gfx_printf("Nowe u hav a rel liv Arceus!!!!!\n");
                if (B == 494) gfx_printf("Nowe u hav a rel liv Victini!!!!!\n");
                if (B == 495) gfx_printf("Nowe u hav a rel liv Snivy!!!!!\n");
                if (B == 496) gfx_printf("Nowe u hav a rel liv Servine!!!!!\n");
                if (B == 497) gfx_printf("Nowe u hav a rel liv Serperior!!!!!\n");
                if (B == 498) gfx_printf("Nowe u hav a rel liv Tepig!!!!!\n");
                if (B == 499) gfx_printf("Nowe u hav a rel liv Pignite!!!!!\n");
                if (B == 500) gfx_printf("Nowe u hav a rel liv Emboar!!!!!\n");
                if (B == 501) gfx_printf("Nowe u hav a rel liv Oshawott!!!!!\n");
                if (B == 502) gfx_printf("Nowe u hav a rel liv Dewott!!!!!\n");
                if (B == 503) gfx_printf("Nowe u hav a rel liv Samurott!!!!!\n");
                if (B == 504) gfx_printf("Nowe u hav a rel liv Patrat!!!!!\n");
                if (B == 505) gfx_printf("Nowe u hav a rel liv Watchog!!!!!\n");
                if (B == 506) gfx_printf("Nowe u hav a rel liv Lillipup!!!!!\n");
                if (B == 507) gfx_printf("Nowe u hav a rel liv Herdier!!!!!\n");
                if (B == 508) gfx_printf("Nowe u hav a rel liv Stoutland!!!!!\n");
                if (B == 509) gfx_printf("Nowe u hav a rel liv Purrloin!!!!!\n");
                if (B == 510) gfx_printf("Nowe u hav a rel liv Liepard!!!!!\n");
                if (B == 511) gfx_printf("Nowe u hav a rel liv Pansage!!!!!\n");
                if (B == 512) gfx_printf("Nowe u hav a rel liv Simisage!!!!!\n");
                if (B == 513) gfx_printf("Nowe u hav a rel liv Pansear!!!!!\n");
                if (B == 514) gfx_printf("Nowe u hav a rel liv Simisear!!!!!\n");
                if (B == 515) gfx_printf("Nowe u hav a rel liv Panpour!!!!!\n");
                if (B == 516) gfx_printf("Nowe u hav a rel liv Simipour!!!!!\n");
                if (B == 517) gfx_printf("Nowe u hav a rel liv Munna!!!!!\n");
                if (B == 518) gfx_printf("Nowe u hav a rel liv Musharna!!!!!\n");
                if (B == 519) gfx_printf("Nowe u hav a rel liv Pidove!!!!!\n");
                if (B == 520) gfx_printf("Nowe u hav a rel liv Tranquill!!!!!\n");
                if (B == 521) gfx_printf("Nowe u hav a rel liv Unfezant!!!!!\n");
                if (B == 522) gfx_printf("Nowe u hav a rel liv Blitzle!!!!!\n");
                if (B == 523) gfx_printf("Nowe u hav a rel liv Zebstrika!!!!!\n");
                if (B == 524) gfx_printf("Nowe u hav a rel liv Roggenrola!!!!!\n");
                if (B == 525) gfx_printf("Nowe u hav a rel liv Boldore!!!!!\n");
                if (B == 526) gfx_printf("Nowe u hav a rel liv Gigalith!!!!!\n");
                if (B == 527) gfx_printf("Nowe u hav a rel liv Woobat!!!!!\n");
                if (B == 528) gfx_printf("Nowe u hav a rel liv Swoobat!!!!!\n");
                if (B == 529) gfx_printf("Nowe u hav a rel liv Drilbur!!!!!\n");
                if (B == 530) gfx_printf("Nowe u hav a rel liv Excadrill!!!!!\n");
                if (B == 531) gfx_printf("Nowe u hav a rel liv Audino!!!!!\n");
                if (B == 532) gfx_printf("Nowe u hav a rel liv Timburr!!!!!\n");
                if (B == 533) gfx_printf("Nowe u hav a rel liv Gurdurr!!!!!\n");
                if (B == 534) gfx_printf("Nowe u hav a rel liv Conkeldurr!!!!!\n");
                if (B == 535) gfx_printf("Nowe u hav a rel liv Tympole!!!!!\n");
                if (B == 536) gfx_printf("Nowe u hav a rel liv Palpitoad!!!!!\n");
                if (B == 537) gfx_printf("Nowe u hav a rel liv Seismitoad!!!!!\n");
                if (B == 538) gfx_printf("Nowe u hav a rel liv Throh!!!!!\n");
                if (B == 539) gfx_printf("Nowe u hav a rel liv Sawk!!!!!\n");
                if (B == 540) gfx_printf("Nowe u hav a rel liv Sewaddle!!!!!\n");
                if (B == 541) gfx_printf("Nowe u hav a rel liv Swadloon!!!!!\n");
                if (B == 542) gfx_printf("Nowe u hav a rel liv Leavanny!!!!!\n");
                if (B == 543) gfx_printf("Nowe u hav a rel liv Venipede!!!!!\n");
                if (B == 544) gfx_printf("Nowe u hav a rel liv Whirlipede!!!!!\n");
                if (B == 545) gfx_printf("Nowe u hav a rel liv Scolipede!!!!!\n");
                if (B == 546) gfx_printf("Nowe u hav a rel liv Cottonee!!!!!\n");
                if (B == 547) gfx_printf("Nowe u hav a rel liv Whimsicott!!!!!\n");
                if (B == 548) gfx_printf("Nowe u hav a rel liv Petilil!!!!!\n");
                if (B == 549) gfx_printf("Nowe u hav a rel liv Lilligant!!!!!\n");
                if (B == 550) gfx_printf("Nowe u hav a rel liv Basculin!!!!!\n");
                if (B == 551) gfx_printf("Nowe u hav a rel liv Sandile!!!!!\n");
                if (B == 552) gfx_printf("Nowe u hav a rel liv Krokorok!!!!!\n");
                if (B == 553) gfx_printf("Nowe u hav a rel liv Krookodile!!!!!\n");
                if (B == 554) gfx_printf("Nowe u hav a rel liv Darumaka!!!!!\n");
                if (B == 555) gfx_printf("Nowe u hav a rel liv Darmanitan!!!!!\n");
                if (B == 556) gfx_printf("Nowe u hav a rel liv Maractus!!!!!\n");
                if (B == 557) gfx_printf("Nowe u hav a rel liv Dwebble!!!!!\n");
                if (B == 558) gfx_printf("Nowe u hav a rel liv Crustle!!!!!\n");
                if (B == 559) gfx_printf("Nowe u hav a rel liv Scraggy!!!!!\n");
                if (B == 560) gfx_printf("Nowe u hav a rel liv Scrafty!!!!!\n");
                if (B == 561) gfx_printf("Nowe u hav a rel liv Sigilyph!!!!!\n");
                if (B == 562) gfx_printf("Nowe u hav a rel liv Yamask!!!!!\n");
                if (B == 563) gfx_printf("Nowe u hav a rel liv Cofagrigus!!!!!\n");
                if (B == 564) gfx_printf("Nowe u hav a rel liv Tirtouga!!!!!\n");
                if (B == 565) gfx_printf("Nowe u hav a rel liv Carracosta!!!!!\n");
                if (B == 566) gfx_printf("Nowe u hav a rel liv Archen!!!!!\n");
                if (B == 567) gfx_printf("Nowe u hav a rel liv Archeops!!!!!\n");
                if (B == 568) gfx_printf("Nowe u hav a rel liv Trubbish!!!!!\n");
                if (B == 569) gfx_printf("Nowe u hav a rel liv Garbodor!!!!!\n");
                if (B == 570) gfx_printf("Nowe u hav a rel liv Zorua!!!!!\n");
                if (B == 571) gfx_printf("Nowe u hav a rel liv Zoroark!!!!!\n");
                if (B == 572) gfx_printf("Nowe u hav a rel liv Minccino!!!!!\n");
                if (B == 573) gfx_printf("Nowe u hav a rel liv Cinccino!!!!!\n");
                if (B == 574) gfx_printf("Nowe u hav a rel liv Gothita!!!!!\n");
                if (B == 575) gfx_printf("Nowe u hav a rel liv Gothorita!!!!!\n");
                if (B == 576) gfx_printf("Nowe u hav a rel liv Gothitelle!!!!!\n");
                if (B == 577) gfx_printf("Nowe u hav a rel liv Solosis!!!!!\n");
                if (B == 578) gfx_printf("Nowe u hav a rel liv Duosion!!!!!\n");
                if (B == 579) gfx_printf("Nowe u hav a rel liv Reuniclus!!!!!\n");
                if (B == 580) gfx_printf("Nowe u hav a rel liv Ducklett!!!!!\n");
                if (B == 581) gfx_printf("Nowe u hav a rel liv Swanna!!!!!\n");
                if (B == 582) gfx_printf("Nowe u hav a rel liv Vanillite!!!!!\n");
                if (B == 583) gfx_printf("Nowe u hav a rel liv Vanillish!!!!!\n");
                if (B == 584) gfx_printf("Nowe u hav a rel liv Vanilluxe!!!!!\n");
                if (B == 585) gfx_printf("Nowe u hav a rel liv Deerling!!!!!\n");
                if (B == 586) gfx_printf("Nowe u hav a rel liv Sawsbuck!!!!!\n");
                if (B == 587) gfx_printf("Nowe u hav a rel liv Emolga!!!!!\n");
                if (B == 588) gfx_printf("Nowe u hav a rel liv Karrablast!!!!!\n");
                if (B == 589) gfx_printf("Nowe u hav a rel liv Escavalier!!!!!\n");
                if (B == 590) gfx_printf("Nowe u hav a rel liv Foongus!!!!!\n");
                if (B == 591) gfx_printf("Nowe u hav a rel liv Amoonguss!!!!!\n");
                if (B == 592) gfx_printf("Nowe u hav a rel liv Frillish!!!!!\n");
                if (B == 593) gfx_printf("Nowe u hav a rel liv Jellicent!!!!!\n");
                if (B == 594) gfx_printf("Nowe u hav a rel liv Alomomola!!!!!\n");
                if (B == 595) gfx_printf("Nowe u hav a rel liv Joltik!!!!!\n");
                if (B == 596) gfx_printf("Nowe u hav a rel liv Galvantula!!!!!\n");
                if (B == 597) gfx_printf("Nowe u hav a rel liv Ferroseed!!!!!\n");
                if (B == 598) gfx_printf("Nowe u hav a rel liv Ferrothorn!!!!!\n");
                if (B == 599) gfx_printf("Nowe u hav a rel liv Klink!!!!!\n");
                if (B == 600) gfx_printf("Nowe u hav a rel liv Klang!!!!!\n");
                if (B == 601) gfx_printf("Nowe u hav a rel liv Klinklang!!!!!\n");
                if (B == 602) gfx_printf("Nowe u hav a rel liv Tynamo!!!!!\n");
                if (B == 603) gfx_printf("Nowe u hav a rel liv Eelektrik!!!!!\n");
                if (B == 604) gfx_printf("Nowe u hav a rel liv Eelektross!!!!!\n");
                if (B == 605) gfx_printf("Nowe u hav a rel liv Elgyem!!!!!\n");
                if (B == 606) gfx_printf("Nowe u hav a rel liv Beheeyem!!!!!\n");
                if (B == 607) gfx_printf("Nowe u hav a rel liv Litwick!!!!!\n");
                if (B == 608) gfx_printf("Nowe u hav a rel liv Lampent!!!!!\n");
                if (B == 609) gfx_printf("Nowe u hav a rel liv Chandelure!!!!!\n");
                if (B == 610) gfx_printf("Nowe u hav a rel liv Axew!!!!!\n");
                if (B == 611) gfx_printf("Nowe u hav a rel liv Fraxure!!!!!\n");
                if (B == 612) gfx_printf("Nowe u hav a rel liv Haxorus!!!!!\n");
                if (B == 613) gfx_printf("Nowe u hav a rel liv Cubchoo!!!!!\n");
                if (B == 614) gfx_printf("Nowe u hav a rel liv Beartic!!!!!\n");
                if (B == 615) gfx_printf("Nowe u hav a rel liv Cryogonal!!!!!\n");
                if (B == 616) gfx_printf("Nowe u hav a rel liv Shelmet!!!!!\n");
                if (B == 617) gfx_printf("Nowe u hav a rel liv Accelgor!!!!!\n");
                if (B == 618) gfx_printf("Nowe u hav a rel liv Stunfisk!!!!!\n");
                if (B == 619) gfx_printf("Nowe u hav a rel liv Mienfoo!!!!!\n");
                if (B == 620) gfx_printf("Nowe u hav a rel liv Mienshao!!!!!\n");
                if (B == 621) gfx_printf("Nowe u hav a rel liv Druddigon!!!!!\n");
                if (B == 622) gfx_printf("Nowe u hav a rel liv Golett!!!!!\n");
                if (B == 623) gfx_printf("Nowe u hav a rel liv Golurk!!!!!\n");
                if (B == 624) gfx_printf("Nowe u hav a rel liv Pawniard!!!!!\n");
                if (B == 625) gfx_printf("Nowe u hav a rel liv Bisharp!!!!!\n");
                if (B == 626) gfx_printf("Nowe u hav a rel liv Bouffalant!!!!!\n");
                if (B == 627) gfx_printf("Nowe u hav a rel liv Rufflet!!!!!\n");
                if (B == 628) gfx_printf("Nowe u hav a rel liv Braviary!!!!!\n");
                if (B == 629) gfx_printf("Nowe u hav a rel liv Vullaby!!!!!\n");
                if (B == 630) gfx_printf("Nowe u hav a rel liv Mandibuzz!!!!!\n");
                if (B == 631) gfx_printf("Nowe u hav a rel liv Heatmor!!!!!\n");
                if (B == 632) gfx_printf("Nowe u hav a rel liv Durant!!!!!\n");
                if (B == 633) gfx_printf("Nowe u hav a rel liv Deino!!!!!\n");
                if (B == 634) gfx_printf("Nowe u hav a rel liv Zweilous!!!!!\n");
                if (B == 635) gfx_printf("Nowe u hav a rel liv Hydreigon!!!!!\n");
                if (B == 636) gfx_printf("Nowe u hav a rel liv Larvesta!!!!!\n");
                if (B == 637) gfx_printf("Nowe u hav a rel liv Volcarona!!!!!\n");
                if (B == 638) gfx_printf("Nowe u hav a rel liv Cobalion!!!!!\n");
                if (B == 639) gfx_printf("Nowe u hav a rel liv Terrakion!!!!!\n");
                if (B == 640) gfx_printf("Nowe u hav a rel liv Virizion!!!!!\n");
                if (B == 641) gfx_printf("Nowe u hav a rel liv Tornadus!!!!!\n");
                if (B == 642) gfx_printf("Nowe u hav a rel liv Thundurus!!!!!\n");
                if (B == 643) gfx_printf("Nowe u hav a rel liv Reshiram!!!!!\n");
                if (B == 644) gfx_printf("Nowe u hav a rel liv Zekrom!!!!!\n");
                if (B == 645) gfx_printf("Nowe u hav a rel liv Landorus!!!!!\n");
                if (B == 646) gfx_printf("Nowe u hav a rel liv Kyurem!!!!!\n");
                if (B == 647) gfx_printf("Nowe u hav a rel liv Keldeo!!!!!\n");
                if (B == 648) gfx_printf("Nowe u hav a rel liv Meloetta!!!!!\n");
                if (B == 649) gfx_printf("Nowe u hav a rel liv Genesect!!!!!\n");
                if (B == 650) gfx_printf("Nowe u hav a rel liv Chespin!!!!!\n");
                if (B == 651) gfx_printf("Nowe u hav a rel liv Quilladin!!!!!\n");
                if (B == 652) gfx_printf("Nowe u hav a rel liv Chesnaught!!!!!\n");
                if (B == 653) gfx_printf("Nowe u hav a rel liv Fennekin!!!!!\n");
                if (B == 654) gfx_printf("Nowe u hav a rel liv Braixen!!!!!\n");
                if (B == 655) gfx_printf("Nowe u hav a rel liv Delphox!!!!!\n");
                if (B == 656) gfx_printf("Nowe u hav a rel liv Froakie!!!!!\n");
                if (B == 657) gfx_printf("Nowe u hav a rel liv Frogadier!!!!!\n");
                if (B == 658) gfx_printf("Nowe u hav a rel liv Greninja!!!!!\n");
                if (B == 659) gfx_printf("Nowe u hav a rel liv Bunnelby!!!!!\n");
                if (B == 660) gfx_printf("Nowe u hav a rel liv Diggersby!!!!!\n");
                if (B == 661) gfx_printf("Nowe u hav a rel liv Fletchling!!!!!\n");
                if (B == 662) gfx_printf("Nowe u hav a rel liv Fletchinder!!!!!\n");
                if (B == 663) gfx_printf("Nowe u hav a rel liv Talonflame!!!!!\n");
                if (B == 664) gfx_printf("Nowe u hav a rel liv Scatterbug!!!!!\n");
                if (B == 665) gfx_printf("Nowe u hav a rel liv Spewpa!!!!!\n");
                if (B == 666) gfx_printf("Nowe u hav a rel liv Vivillon!!!!!\n");
                if (B == 667) gfx_printf("Nowe u hav a rel liv Litleo!!!!!\n");
                if (B == 668) gfx_printf("Nowe u hav a rel liv Pyroar!!!!!\n");
                if (B == 669) gfx_printf("Nowe u hav a rel liv Flabébé!!!!!\n");
                if (B == 670) gfx_printf("Nowe u hav a rel liv Floette!!!!!\n");
                if (B == 671) gfx_printf("Nowe u hav a rel liv Florges!!!!!\n");
                if (B == 672) gfx_printf("Nowe u hav a rel liv Skiddo!!!!!\n");
                if (B == 673) gfx_printf("Nowe u hav a rel liv Gogoat!!!!!\n");
                if (B == 674) gfx_printf("Nowe u hav a rel liv Pancham!!!!!\n");
                if (B == 675) gfx_printf("Nowe u hav a rel liv Pangoro!!!!!\n");
                if (B == 676) gfx_printf("Nowe u hav a rel liv Furfrou!!!!!\n");
                if (B == 677) gfx_printf("Nowe u hav a rel liv Espurr!!!!!\n");
                if (B == 678) gfx_printf("Nowe u hav a rel liv Meowstic!!!!!\n");
                if (B == 679) gfx_printf("Nowe u hav a rel liv Honedge!!!!!\n");
                if (B == 680) gfx_printf("Nowe u hav a rel liv Doublade!!!!!\n");
                if (B == 681) gfx_printf("Nowe u hav a rel liv Aegislash!!!!!\n");
                if (B == 682) gfx_printf("Nowe u hav a rel liv Spritzee!!!!!\n");
                if (B == 683) gfx_printf("Nowe u hav a rel liv Aromatisse!!!!!\n");
                if (B == 684) gfx_printf("Nowe u hav a rel liv Swirlix!!!!!\n");
                if (B == 685) gfx_printf("Nowe u hav a rel liv Slurpuff!!!!!\n");
                if (B == 686) gfx_printf("Nowe u hav a rel liv Inkay!!!!!\n");
                if (B == 687) gfx_printf("Nowe u hav a rel liv Malamar!!!!!\n");
                if (B == 688) gfx_printf("Nowe u hav a rel liv Binacle!!!!!\n");
                if (B == 689) gfx_printf("Nowe u hav a rel liv Barbaracle!!!!!\n");
                if (B == 690) gfx_printf("Nowe u hav a rel liv Skrelp!!!!!\n");
                if (B == 691) gfx_printf("Nowe u hav a rel liv Dragalge!!!!!\n");
                if (B == 692) gfx_printf("Nowe u hav a rel liv Clauncher!!!!!\n");
                if (B == 693) gfx_printf("Nowe u hav a rel liv Clawitzer!!!!!\n");
                if (B == 694) gfx_printf("Nowe u hav a rel liv Helioptile!!!!!\n");
                if (B == 695) gfx_printf("Nowe u hav a rel liv Heliolisk!!!!!\n");
                if (B == 696) gfx_printf("Nowe u hav a rel liv Tyrunt!!!!!\n");
                if (B == 697) gfx_printf("Nowe u hav a rel liv Tyrantrum!!!!!\n");
                if (B == 698) gfx_printf("Nowe u hav a rel liv Amaura!!!!!\n");
                if (B == 699) gfx_printf("Nowe u hav a rel liv Aurorus!!!!!\n");
                if (B == 700) gfx_printf("Nowe u hav a rel liv Sylveon!!!!!\n");
                if (B == 701) gfx_printf("Nowe u hav a rel liv Hawlucha!!!!!\n");
                if (B == 702) gfx_printf("Nowe u hav a rel liv Dedenne!!!!!\n");
                if (B == 703) gfx_printf("Nowe u hav a rel liv Carbink!!!!!\n");
                if (B == 704) gfx_printf("Nowe u hav a rel liv Goomy!!!!!\n");
                if (B == 705) gfx_printf("Nowe u hav a rel liv Sliggoo!!!!!\n");
                if (B == 706) gfx_printf("Nowe u hav a rel liv Goodra!!!!!\n");
                if (B == 707) gfx_printf("Nowe u hav a rel liv Klefki!!!!!\n");
                if (B == 708) gfx_printf("Nowe u hav a rel liv Phantump!!!!!\n");
                if (B == 709) gfx_printf("Nowe u hav a rel liv Trevenant!!!!!\n");
                if (B == 710) gfx_printf("Nowe u hav a rel liv Pumpkaboo!!!!!\n");
                if (B == 711) gfx_printf("Nowe u hav a rel liv Gourgeist!!!!!\n");
                if (B == 712) gfx_printf("Nowe u hav a rel liv Bergmite!!!!!\n");
                if (B == 713) gfx_printf("Nowe u hav a rel liv Avalugg!!!!!\n");
                if (B == 714) gfx_printf("Nowe u hav a rel liv Noibat!!!!!\n");
                if (B == 715) gfx_printf("Nowe u hav a rel liv Noivern!!!!!\n");
                if (B == 716) gfx_printf("Nowe u hav a rel liv Xerneas!!!!!\n");
                if (B == 717) gfx_printf("Nowe u hav a rel liv Yveltal!!!!!\n");
                if (B == 718) gfx_printf("Nowe u hav a rel liv Zygarde!!!!!\n");
                if (B == 719) gfx_printf("Nowe u hav a rel liv Diancie!!!!!\n");
                if (B == 720) gfx_printf("Nowe u hav a rel liv Hoopa!!!!!\n");
                if (B == 721) gfx_printf("Nowe u hav a rel liv Volcanion!!!!!\n");
                if (B == 722) gfx_printf("Nowe u hav a rel liv Rowlet!!!!!\n");
                if (B == 723) gfx_printf("Nowe u hav a rel liv Dartrix!!!!!\n");
                if (B == 724) gfx_printf("Nowe u hav a rel liv Decidueye!!!!!\n");
                if (B == 725) gfx_printf("Nowe u hav a rel liv Litten!!!!!\n");
                if (B == 726) gfx_printf("Nowe u hav a rel liv Torracat!!!!!\n");
                if (B == 727) gfx_printf("Nowe u hav a rel liv Incineroar!!!!!\n");
                if (B == 728) gfx_printf("Nowe u hav a rel liv Popplio!!!!!\n");
                if (B == 729) gfx_printf("Nowe u hav a rel liv Brionne!!!!!\n");
                if (B == 730) gfx_printf("Nowe u hav a rel liv Primarina!!!!!\n");
                if (B == 731) gfx_printf("Nowe u hav a rel liv Pikipek!!!!!\n");
                if (B == 732) gfx_printf("Nowe u hav a rel liv Trumbeak!!!!!\n");
                if (B == 733) gfx_printf("Nowe u hav a rel liv Toucannon!!!!!\n");
                if (B == 734) gfx_printf("Nowe u hav a rel liv Yungoos!!!!!\n");
                if (B == 735) gfx_printf("Nowe u hav a rel liv Gumshoos!!!!!\n");
                if (B == 736) gfx_printf("Nowe u hav a rel liv Grubbin!!!!!\n");
                if (B == 737) gfx_printf("Nowe u hav a rel liv Charjabug!!!!!\n");
                if (B == 738) gfx_printf("Nowe u hav a rel liv Vikavolt!!!!!\n");
                if (B == 739) gfx_printf("Nowe u hav a rel liv Crabrawler!!!!!\n");
                if (B == 740) gfx_printf("Nowe u hav a rel liv Crabominable!!!!!\n");
                if (B == 741) gfx_printf("Nowe u hav a rel liv Oricorio!!!!!\n");
                if (B == 742) gfx_printf("Nowe u hav a rel liv Cutiefly!!!!!\n");
                if (B == 743) gfx_printf("Nowe u hav a rel liv Ribombee!!!!!\n");
                if (B == 744) gfx_printf("Nowe u hav a rel liv Rockruff!!!!!\n");
                if (B == 745) gfx_printf("Nowe u hav a rel liv Lycanroc!!!!!\n");
                if (B == 746) gfx_printf("Nowe u hav a rel liv Wishiwashi!!!!!\n");
                if (B == 747) gfx_printf("Nowe u hav a rel liv Mareanie!!!!!\n");
                if (B == 748) gfx_printf("Nowe u hav a rel liv Toxapex!!!!!\n");
                if (B == 749) gfx_printf("Nowe u hav a rel liv Mudbray!!!!!\n");
                if (B == 750) gfx_printf("Nowe u hav a rel liv Mudsdale!!!!!\n");
                if (B == 751) gfx_printf("Nowe u hav a rel liv Dewpider!!!!!\n");
                if (B == 752) gfx_printf("Nowe u hav a rel liv Araquanid!!!!!\n");
                if (B == 753) gfx_printf("Nowe u hav a rel liv Fomantis!!!!!\n");
                if (B == 754) gfx_printf("Nowe u hav a rel liv Lurantis!!!!!\n");
                if (B == 755) gfx_printf("Nowe u hav a rel liv Morelull!!!!!\n");
                if (B == 756) gfx_printf("Nowe u hav a rel liv Shiinotic!!!!!\n");
                if (B == 757) gfx_printf("Nowe u hav a rel liv Salandit!!!!!\n");
                if (B == 758) gfx_printf("Nowe u hav a rel liv Salazzle!!!!!\n");
                if (B == 759) gfx_printf("Nowe u hav a rel liv Stufful!!!!!\n");
                if (B == 760) gfx_printf("Nowe u hav a rel liv Bewear!!!!!\n");
                if (B == 761) gfx_printf("Nowe u hav a rel liv Bounsweet!!!!!\n");
                if (B == 762) gfx_printf("Nowe u hav a rel liv Steenee!!!!!\n");
                if (B == 763) gfx_printf("Nowe u hav a rel liv Tsareena!!!!!\n");
                if (B == 764) gfx_printf("Nowe u hav a rel liv Comfey!!!!!\n");
                if (B == 765) gfx_printf("Nowe u hav a rel liv Oranguru!!!!!\n");
                if (B == 766) gfx_printf("Nowe u hav a rel liv Passimian!!!!!\n");
                if (B == 767) gfx_printf("Nowe u hav a rel liv Wimpod!!!!!\n");
                if (B == 768) gfx_printf("Nowe u hav a rel liv Golisopod!!!!!\n");
                if (B == 769) gfx_printf("Nowe u hav a rel liv Sandygast!!!!!\n");
                if (B == 770) gfx_printf("Nowe u hav a rel liv Palossand!!!!!\n");
                if (B == 771) gfx_printf("Nowe u hav a rel liv Pyukumuku!!!!!\n");
                if (B == 772) gfx_printf("Nowe u hav a rel liv Type: Null!!!!!\n");
                if (B == 773) gfx_printf("Nowe u hav a rel liv Silvally!!!!!\n");
                if (B == 774) gfx_printf("Nowe u hav a rel liv Minior!!!!!\n");
                if (B == 775) gfx_printf("Nowe u hav a rel liv Komala!!!!!\n");
                if (B == 776) gfx_printf("Nowe u hav a rel liv Turtonator!!!!!\n");
                if (B == 777) gfx_printf("Nowe u hav a rel liv Togedemaru!!!!!\n");
                if (B == 778) gfx_printf("Nowe u hav a rel liv Mimikyu!!!!!\n");
                if (B == 779) gfx_printf("Nowe u hav a rel liv Bruxish!!!!!\n");
                if (B == 780) gfx_printf("Nowe u hav a rel liv Drampa!!!!!\n");
                if (B == 781) gfx_printf("Nowe u hav a rel liv Dhelmise!!!!!\n");
                if (B == 782) gfx_printf("Nowe u hav a rel liv Jangmo-o!!!!!\n");
                if (B == 783) gfx_printf("Nowe u hav a rel liv Hakamo-o!!!!!\n");
                if (B == 784) gfx_printf("Nowe u hav a rel liv Kommo-o!!!!!\n");
                if (B == 785) gfx_printf("Nowe u hav a rel liv Tapu Koko!!!!!\n");
                if (B == 786) gfx_printf("Nowe u hav a rel liv Tapu Lele!!!!!\n");
                if (B == 787) gfx_printf("Nowe u hav a rel liv Tapu Bulu!!!!!\n");
                if (B == 788) gfx_printf("Nowe u hav a rel liv Tapu Fini!!!!!\n");
                if (B == 789) gfx_printf("Nowe u hav a rel liv Cosmog!!!!!\n");
                if (B == 790) gfx_printf("Nowe u hav a rel liv Cosmoem!!!!!\n");
                if (B == 791) gfx_printf("Nowe u hav a rel liv Solgaleo!!!!!\n");
                if (B == 792) gfx_printf("Nowe u hav a rel liv Lunala!!!!!\n");
                if (B == 793) gfx_printf("Nowe u hav a rel liv Nihilego!!!!!\n");
                if (B == 794) gfx_printf("Nowe u hav a rel liv Buzzwole!!!!!\n");
                if (B == 795) gfx_printf("Nowe u hav a rel liv Pheromosa!!!!!\n");
                if (B == 796) gfx_printf("Nowe u hav a rel liv Xurkitree!!!!!\n");
                if (B == 797) gfx_printf("Nowe u hav a rel liv Celesteela!!!!!\n");
                if (B == 798) gfx_printf("Nowe u hav a rel liv Kartana!!!!!\n");
                if (B == 799) gfx_printf("Nowe u hav a rel liv Guzzlord!!!!!\n");
                if (B == 800) gfx_printf("Nowe u hav a rel liv Necrozma!!!!!\n");
                if (B == 801) gfx_printf("Nowe u hav a rel liv Magearna!!!!!\n");
                if (B == 802) gfx_printf("Nowe u hav a rel liv Marshadow!!!!!\n");
                if (B == 803) gfx_printf("Nowe u hav a rel liv Poipole!!!!!\n");
                if (B == 804) gfx_printf("Nowe u hav a rel liv Naganadel!!!!!\n");
                if (B == 805) gfx_printf("Nowe u hav a rel liv Stakataka!!!!!\n");
                if (B == 806) gfx_printf("Nowe u hav a rel liv Blacephalon!!!!!\n");
                if (B == 807) gfx_printf("Nowe u hav a rel liv Zeraora!!!!!\n");
                if (B == 808) gfx_printf("Nowe u hav a rel liv Meltan!!!!!\n");
                if (B == 809) gfx_printf("Nowe u hav a rel liv Melmetal!!!!!\n");
                if (B == 810) gfx_printf("Nowe u hav a rel liv Grookey!!!!!\n");
                if (B == 811) gfx_printf("Nowe u hav a rel liv Thwackey!!!!!\n");
                if (B == 812) gfx_printf("Nowe u hav a rel liv Rillaboom!!!!!\n");
                if (B == 813) gfx_printf("Nowe u hav a rel liv Scorbunny!!!!!\n");
                if (B == 814) gfx_printf("Nowe u hav a rel liv Raboot!!!!!\n");
                if (B == 815) gfx_printf("Nowe u hav a rel liv Cinderace!!!!!\n");
                if (B == 816) gfx_printf("Nowe u hav a rel liv Sobble!!!!!\n");
                if (B == 817) gfx_printf("Nowe u hav a rel liv Drizzile!!!!!\n");
                if (B == 818) gfx_printf("Nowe u hav a rel liv Inteleon!!!!!\n");
                if (B == 819) gfx_printf("Nowe u hav a rel liv Skwovet!!!!!\n");
                if (B == 820) gfx_printf("Nowe u hav a rel liv Greedent!!!!!\n");
                if (B == 821) gfx_printf("Nowe u hav a rel liv Rookidee!!!!!\n");
                if (B == 822) gfx_printf("Nowe u hav a rel liv Corvisquire!!!!!\n");
                if (B == 823) gfx_printf("Nowe u hav a rel liv Corviknight!!!!!\n");
                if (B == 824) gfx_printf("Nowe u hav a rel liv Blipbug!!!!!\n");
                if (B == 825) gfx_printf("Nowe u hav a rel liv Dottler!!!!!\n");
                if (B == 826) gfx_printf("Nowe u hav a rel liv Orbeetle!!!!!\n");
                if (B == 827) gfx_printf("Nowe u hav a rel liv Nickit!!!!!\n");
                if (B == 828) gfx_printf("Nowe u hav a rel liv Thievul!!!!!\n");
                if (B == 829) gfx_printf("Nowe u hav a rel liv Gossifleur!!!!!\n");
                if (B == 830) gfx_printf("Nowe u hav a rel liv Eldegoss!!!!!\n");
                if (B == 831) gfx_printf("Nowe u hav a rel liv Wooloo!!!!!\n");
                if (B == 832) gfx_printf("Nowe u hav a rel liv Dubwool!!!!!\n");
                if (B == 833) gfx_printf("Nowe u hav a rel liv Chewtle!!!!!\n");
                if (B == 834) gfx_printf("Nowe u hav a rel liv Drednaw!!!!!\n");
                if (B == 835) gfx_printf("Nowe u hav a rel liv Yamper!!!!!\n");
                if (B == 836) gfx_printf("Nowe u hav a rel liv Boltund!!!!!\n");
                if (B == 837) gfx_printf("Nowe u hav a rel liv Rolycoly!!!!!\n");
                if (B == 838) gfx_printf("Nowe u hav a rel liv Carkol!!!!!\n");
                if (B == 839) gfx_printf("Nowe u hav a rel liv Coalossal!!!!!\n");
                if (B == 840) gfx_printf("Nowe u hav a rel liv Applin!!!!!\n");
                if (B == 841) gfx_printf("Nowe u hav a rel liv Flapple!!!!!\n");
                if (B == 842) gfx_printf("Nowe u hav a rel liv Appletun!!!!!\n");
                if (B == 843) gfx_printf("Nowe u hav a rel liv Silicobra!!!!!\n");
                if (B == 844) gfx_printf("Nowe u hav a rel liv Sandaconda!!!!!\n");
                if (B == 845) gfx_printf("Nowe u hav a rel liv Cramorant!!!!!\n");
                if (B == 846) gfx_printf("Nowe u hav a rel liv Arrokuda!!!!!\n");
                if (B == 847) gfx_printf("Nowe u hav a rel liv Barraskewda!!!!!\n");
                if (B == 848) gfx_printf("Nowe u hav a rel liv Toxel!!!!!\n");
                if (B == 849) gfx_printf("Nowe u hav a rel liv Toxtricity!!!!!\n");
                if (B == 850) gfx_printf("Nowe u hav a rel liv Sizzlipede!!!!!\n");
                if (B == 851) gfx_printf("Nowe u hav a rel liv Centiskorch!!!!!\n");
                if (B == 852) gfx_printf("Nowe u hav a rel liv Clobbopus!!!!!\n");
                if (B == 853) gfx_printf("Nowe u hav a rel liv Grapploct!!!!!\n");
                if (B == 854) gfx_printf("Nowe u hav a rel liv Sinistea!!!!!\n");
                if (B == 855) gfx_printf("Nowe u hav a rel liv Polteageist!!!!!\n");
                if (B == 856) gfx_printf("Nowe u hav a rel liv Hatenna!!!!!\n");
                if (B == 857) gfx_printf("Nowe u hav a rel liv Hattrem!!!!!\n");
                if (B == 858) gfx_printf("Nowe u hav a rel liv Hatterene!!!!!\n");
                if (B == 859) gfx_printf("Nowe u hav a rel liv Impidimp!!!!!\n");
                if (B == 860) gfx_printf("Nowe u hav a rel liv Morgrem!!!!!\n");
                if (B == 861) gfx_printf("Nowe u hav a rel liv Grimmsnarl!!!!!\n");
                if (B == 862) gfx_printf("Nowe u hav a rel liv Obstagoon!!!!!\n");
                if (B == 863) gfx_printf("Nowe u hav a rel liv Perrserker!!!!!\n");
                if (B == 864) gfx_printf("Nowe u hav a rel liv Cursola!!!!!\n");
                if (B == 865) gfx_printf("Nowe u hav a rel liv Sirfetch'd!!!!!\n");
                if (B == 866) gfx_printf("Nowe u hav a rel liv Mr. Rime!!!!!\n");
                if (B == 867) gfx_printf("Nowe u hav a rel liv Runerigus!!!!!\n");
                if (B == 868) gfx_printf("Nowe u hav a rel liv Milcery!!!!!\n");
                if (B == 869) gfx_printf("Nowe u hav a rel liv Alcremie!!!!!\n");
                if (B == 870) gfx_printf("Nowe u hav a rel liv Falinks!!!!!\n");
                if (B == 871) gfx_printf("Nowe u hav a rel liv Pincurchin!!!!!\n");
                if (B == 872) gfx_printf("Nowe u hav a rel liv Snom!!!!!\n");
                if (B == 873) gfx_printf("Nowe u hav a rel liv Frosmoth!!!!!\n");
                if (B == 874) gfx_printf("Nowe u hav a rel liv Stonjourner!!!!!\n");
                if (B == 875) gfx_printf("Nowe u hav a rel liv Eiscue!!!!!\n");
                if (B == 876) gfx_printf("Nowe u hav a rel liv Indeedee!!!!!\n");
                if (B == 877) gfx_printf("Nowe u hav a rel liv Morpeko!!!!!\n");
                if (B == 878) gfx_printf("Nowe u hav a rel liv Cufant!!!!!\n");
                if (B == 879) gfx_printf("Nowe u hav a rel liv Copperajah!!!!!\n");
                if (B == 880) gfx_printf("Nowe u hav a rel liv Dracozolt!!!!!\n");
                if (B == 881) gfx_printf("Nowe u hav a rel liv Arctozolt!!!!!\n");
                if (B == 882) gfx_printf("Nowe u hav a rel liv Dracovish!!!!!\n");
                if (B == 883) gfx_printf("Nowe u hav a rel liv Arctovish!!!!!\n");
                if (B == 884) gfx_printf("Nowe u hav a rel liv Duraludon!!!!!\n");
                if (B == 885) gfx_printf("Nowe u hav a rel liv Dreepy!!!!!\n");
                if (B == 886) gfx_printf("Nowe u hav a rel liv Drakloak!!!!!\n");
                if (B == 887) gfx_printf("Nowe u hav a rel liv Dragapult!!!!!\n");
                if (B == 888) gfx_printf("Nowe u hav a rel liv Zacian!!!!!\n");
                if (B == 889) gfx_printf("Nowe u hav a rel liv Zamazenta!!!!!\n");
                if (B == 890) gfx_printf("Nowe u hav a rel liv Eternatus!!!!!\n");
                if (B > 890) B = 0;
}
}

    }
}
